language: fr
lang: fr-FR
author: "Machou"
robots: "all"
date: 2025-05-08 18:30:00 +0200
published: true
draft: false
toc: false
url: "https://machou.github.io"
markdown: kramdown
# theme: jekyll-theme-cayman

# plugins:
  # - jekyll-feed
  # - jekyll-seo-tag # https://github.com/jekyll/jekyll-seo-tag

sass:
  style: compressed

github_username: Machou

socials:
  GitHub: https://github.com/Machou
  GitLab: https://gitlab.com/Machou
#   twitter:
#   github:
#   linkedin:

markdown_ext: "markdown,mkdn,md"

navbar:
  - title: "Accueil"
    url: "/"
  - title: "Créer un Hidden Service"
    url: "/comment-creer-hidden-service"
  - title: "PortSentry"
    url: "/comment-utiliser-portsentry"
  - title: "Fail2ban"
    url: "/comment-utiliser-portsentry"
  - title: "WoW PNJ LFR"
    url: "/wow-pnj-lfr"

github:
  is_project_page: true
