name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Tous les jours à minuit
  workflow_dispatch:  # Permet l'exécution manuelle
  push:
    branches: [ main ]

jobs:
  generate-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp requests

    - name: Create templates directory
      run: mkdir -p templates

    - name: Generate GitHub Stats
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
      run: |
        python generate_images.py

    - name: List generated files
      run: |
        echo "Generated files:"
        ls -la generated/ || echo "No generated folder found"

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add generated/ || true
        git diff --staged --quiet || git commit -m "Update GitHub stats"
        git push || true
