name: Generate Stats Images

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 1,15 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: 'x64'
        cache: 'pip'

    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    - name: Commit to the repo
      run: |
        git config user.name "Machou"
        git config user.email "github-stats[bot]@machou.github.io"
        git add .
        git commit -m 'Update Images generated files' || true
        git push
